error: called `unwrap` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:13:9
   |
LL |     if x.is_ok() && y.is_err() {
   |        --------- the check is happening here
LL |         // unnecessary
LL |         x.unwrap();
   |         ^^^^^^^^^^
   |
   = help: try using `if let` or `match`
note: the lint level is defined here
  --> tests/ui/checked_unwrap/complex_conditionals.rs:1:35
   |
LL | #![deny(clippy::panicking_unwrap, clippy::unnecessary_unwrap)]
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:17:9
   |
LL |     if x.is_ok() && y.is_err() {
   |        --------- because of this check
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> tests/ui/checked_unwrap/complex_conditionals.rs:1:9
   |
LL | #![deny(clippy::panicking_unwrap, clippy::unnecessary_unwrap)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:21:9
   |
LL |     if x.is_ok() && y.is_err() {
   |                     ---------- because of this check
...
LL |         y.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `y` after checking its variant with `is_err`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:25:9
   |
LL |     if x.is_ok() && y.is_err() {
   |                     ---------- the check is happening here
...
LL |         y.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:42:9
   |
LL |     if x.is_ok() || y.is_ok() {
   |        --------- because of this check
...
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:46:9
   |
LL |     if x.is_ok() || y.is_ok() {
   |        --------- the check is happening here
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:50:9
   |
LL |     if x.is_ok() || y.is_ok() {
   |                     --------- because of this check
...
LL |         y.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `y` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:54:9
   |
LL |     if x.is_ok() || y.is_ok() {
   |                     --------- the check is happening here
...
LL |         y.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: called `unwrap` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:61:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |        --------- the check is happening here
LL |         // unnecessary
LL |         x.unwrap();
   |         ^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:65:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |        --------- because of this check
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:69:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |                       --------- because of this check
...
LL |         y.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `y` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:73:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |                       --------- the check is happening here
...
LL |         y.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: called `unwrap` on `z` after checking its variant with `is_err`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:77:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |                                    ---------- the check is happening here
...
LL |         z.unwrap();
   |         ^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:81:9
   |
LL |     if x.is_ok() && !(y.is_ok() || z.is_err()) {
   |                                    ---------- because of this check
...
LL |         z.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:92:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |        --------- because of this check
...
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:96:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |        --------- the check is happening here
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: called `unwrap` on `y` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:100:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |                       --------- the check is happening here
...
LL |         y.unwrap();
   |         ^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:104:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |                       --------- because of this check
...
LL |         y.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/complex_conditionals.rs:108:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |                                    ---------- because of this check
...
LL |         z.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `z` after checking its variant with `is_err`
  --> tests/ui/checked_unwrap/complex_conditionals.rs:112:9
   |
LL |     if x.is_ok() || !(y.is_ok() && z.is_err()) {
   |                                    ---------- the check is happening here
...
LL |         z.unwrap_err();
   |         ^^^^^^^^^^^^^^
   |
   = help: try using `if let` or `match`

error: aborting due to 20 previous errors

