error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:11:5
   |
LL | /     fn a(&self) -> &u8 {
LL | |         &self.b
   | |         ------- help: consider using: `&self.a`
LL | |     }
   | |_____^
   |
   = note: `-D clippy::misnamed-getters` implied by `-D warnings`

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:14:5
   |
LL | /     fn a_mut(&mut self) -> &mut u8 {
LL | |         &mut self.b
   | |         ----------- help: consider using: `&mut self.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:18:5
   |
LL | /     fn b(self) -> u8 {
LL | |         self.a
   | |         ------ help: consider using: `self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:22:5
   |
LL | /     fn b_mut(&mut self) -> &mut u8 {
LL | |         &mut self.a
   | |         ----------- help: consider using: `&mut self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:26:5
   |
LL | /     fn c(&self) -> &u8 {
LL | |         &self.b
   | |         ------- help: consider using: `&self.c`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:30:5
   |
LL | /     fn c_mut(&mut self) -> &mut u8 {
LL | |         &mut self.a
   | |         ----------- help: consider using: `&mut self.c`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:41:5
   |
LL | /     unsafe fn a(&self) -> &u8 {
LL | |         &self.b
   | |         ------- help: consider using: `&self.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:44:5
   |
LL | /     unsafe fn a_mut(&mut self) -> &mut u8 {
LL | |         &mut self.b
   | |         ----------- help: consider using: `&mut self.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:48:5
   |
LL | /     unsafe fn b(self) -> u8 {
LL | |         self.a
   | |         ------ help: consider using: `self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:52:5
   |
LL | /     unsafe fn b_mut(&mut self) -> &mut u8 {
LL | |         &mut self.a
   | |         ----------- help: consider using: `&mut self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:64:5
   |
LL | /     unsafe fn a_unchecked(&self) -> &u8 {
LL | |         &self.b
   | |         ------- help: consider using: `&self.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:67:5
   |
LL | /     unsafe fn a_unchecked_mut(&mut self) -> &mut u8 {
LL | |         &mut self.b
   | |         ----------- help: consider using: `&mut self.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:71:5
   |
LL | /     unsafe fn b_unchecked(self) -> u8 {
LL | |         self.a
   | |         ------ help: consider using: `self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:75:5
   |
LL | /     unsafe fn b_unchecked_mut(&mut self) -> &mut u8 {
LL | |         &mut self.a
   | |         ----------- help: consider using: `&mut self.b`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:92:5
   |
LL | /     unsafe fn a(&self) -> &u8 {
LL | |         &self.inner.b
   | |         ------------- help: consider using: `&self.inner.a`
LL | |     }
   | |_____^

error: getter function appears to return the wrong field
  --> $DIR/misnamed_getters.rs:95:5
   |
LL | /     unsafe fn a_mut(&mut self) -> &mut u8 {
LL | |         &mut self.inner.b
   | |         ----------------- help: consider using: `&mut self.inner.a`
LL | |     }
   | |_____^

error: aborting due to 16 previous errors

