error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:50:5
   |
LL | /     pub fn new(_: String) -> impl R<Item = u32> {
...  |
LL | |     }
   | |_____^
   |
   = note: `-D clippy::new-ret-no-self` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::new_ret_no_self)]`

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:85:5
   |
LL | /     pub fn new() -> u32 {
LL | |
LL | |
LL | |         unimplemented!();
LL | |     }
   | |_____^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:96:5
   |
LL | /     pub fn new(_: String) -> u32 {
LL | |
LL | |
LL | |         unimplemented!();
LL | |     }
   | |_____^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:134:5
   |
LL | /     pub fn new() -> (u32, u32) {
LL | |
LL | |
LL | |         unimplemented!();
LL | |     }
   | |_____^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:163:5
   |
LL | /     pub fn new() -> *mut V {
LL | |
LL | |
LL | |         unimplemented!();
LL | |     }
   | |_____^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:183:5
   |
LL | /     pub fn new() -> Option<u32> {
LL | |
LL | |
LL | |         unimplemented!();
LL | |     }
   | |_____^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:238:9
   |
LL |         fn new() -> String;
   |         ^^^^^^^^^^^^^^^^^^^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:252:9
   |
LL |         fn new(_: String) -> String;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:289:9
   |
LL | /         fn new() -> (u32, u32) {
LL | |
LL | |
LL | |             unimplemented!();
LL | |         }
   | |_________^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:318:9
   |
LL | /         fn new() -> *mut V {
LL | |
LL | |
LL | |             unimplemented!();
LL | |         }
   | |_________^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:390:9
   |
LL | /         fn new(t: T) -> impl Into<i32> {
LL | |
LL | |
LL | |             1
LL | |         }
   | |_________^

error: methods called `new` usually return `Self`
  --> tests/ui/new_ret_no_self.rs:411:9
   |
LL | /         fn new(t: T) -> impl Trait2<(), i32> {
...  |
LL | |         }
   | |_________^

error: aborting due to 12 previous errors

